apiVersion: apps/v1
kind: Deployment
metadata:
    name: componentProcessingSvc-deployment
    labels:
      app: componentProcessingSvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: componentProcessingSvc      
  template:
    metadata:
      labels:
        app: componentProcessingSvc
    spec:
      containers:
        - name: componentprocessingsvc
          image: returnordercr.azurecr.io/componentprocessingserviceimage:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: returnordersvcsecret

---

apiVersion: v1
kind: Service
metadata:
  name: componentprocessingsvcservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
      app: componentProcessingSvc      
    
    