apiVersion: apps/v1
kind: Deployment
metadata:
    name: componentProcessingsvc-deployment
    labels:
      app: ReturnOrderAKSConnection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReturnOrderAKSConnection      
  template:
    metadata:
      labels:
        app: ReturnOrderAKSConnection
    spec:
      containers:
        - name: ReturnOrderAKSConnection
          image: returnordercr.azurecr.io/componentprocessingserviceimage:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: returnordersvcsecret

---

apiVersion: v1
kind: Service
metadata:
  name: componentprocessingsvcservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
      app: ReturnOrderAKSConnection      
    
    